### ISSUE TITLE
Hekalain running panic if is built under go1.6.x 

### ISSUE THREAD

**Issue by ericpai** [laincloud/hekalain#2]
When starting hekad in Rebellion, it's panic.
Rebellion version: 2.0.2

The output

```
goroutine 30 [running]:
panic(0xacf320, 0xc82000ff20)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/mozilla-services/heka/sandbox/lua._cgoCheckPointer0(0x9b3780, 0xc820275180, 0x0, 0x0, 0x0, 0x7f12ac000900)
    github.com/mozilla-services/heka/sandbox/lua/_obj/_cgo_gotypes.go:65 +0x4d
github.com/mozilla-services/heka/sandbox/lua.CreateLuaSandbox(0xc820234200, 0x0, 0x0, 0x0, 0x0)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/sandbox/lua/lua_sandbox.go:697 +0x92a
github.com/mozilla-services/heka/sandbox/plugins.(*SandboxDecoder).SetDecoderRunner(0xc8202042c0, 0x7f12c2274970, 0xc820216120)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/sandbox/plugins/sandbox_decoder.go:152 +0x120
github.com/mozilla-services/heka/pipeline.(*dRunner).Start(0xc820216120, 0x7f12c2276fc8, 0xc82014e000, 0xc82014e0a0)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:624 +0x160
github.com/mozilla-services/heka/pipeline.(*PipelineConfig).DecoderRunner(0xc82014e000, 0xc820185460, 0x11, 0xc82021aa40, 0x1f, 0x7f12c2274970, 0xc820216120, 0x416b01)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/pipeline/config.go:324 +0x358
github.com/mozilla-services/heka/pipeline.(*iRunner).getDeliverFunc(0xc820230000, 0xc82000fa98, 0x1, 0xc820460000, 0x0, 0x0, 0x0, 0x0)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:452 +0x545
github.com/mozilla-services/heka/pipeline.(*iRunner).NewDeliverer(0xc820230000, 0xc82000fa98, 0x1, 0x0, 0x0)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:514 +0x51
github.com/mozilla-services/heka/plugins/logstreamer.(*LogstreamerInput).startLogstreamInput(0xc82007b080, 0xc82022e000, 0x1, 0x7f12c2275098, 0xc820230000, 0x7f12c2276fc8, 0xc82014e000)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/plugins/logstreamer/logstreamer_input.go:193 +0x8e
github.com/mozilla-services/heka/plugins/logstreamer.(*LogstreamerInput).Run(0xc82007b080, 0x7f12c2275098, 0xc820230000, 0x7f12c2276fc8, 0xc82014e000, 0x0, 0x0)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/plugins/logstreamer/logstreamer_input.go:213 +0x132
github.com/mozilla-services/heka/pipeline.(*iRunner).Starter(0xc820230000, 0x7f12c2276fc8, 0xc82014e000, 0xc82014e18c)
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:325 +0x1b7
created by github.com/mozilla-services/heka/pipeline.(*iRunner).Start
    /heka_build/src/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:305 +0x88d
panic: runtime error: cgo argument has Go pointer to Go pointer
```

Maybe it's caused by the upgrading of Go1.5.x to 1.6.x. It works well under Go1.5.x.
[Here are the changes](https://golang.org/doc/go1.6#cgo)

**Comment by ericpai** [comment]
#https://github.com/laincloud/rebellion/pull/2
